USE [master]
GO

/****** Object:  Database [mem]    Script Date: 11.04.2024 9:49:21 ******/
CREATE DATABASE [mem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\mem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'mem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\mem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mem] SET ARITHABORT OFF 
GO

ALTER DATABASE [mem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mem] SET  MULTI_USER 
GO

ALTER DATABASE [mem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [mem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [mem] SET QUERY_STORE = ON
GO

ALTER DATABASE [mem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [mem] SET  READ_WRITE 
GO

